### ISSUE TITLE
jruby 9.0.0.0.rc1 not working

### ISSUE THREAD

**Issue by ooeyuna** [mrbrdo/theine#18]
Enviroment info

rvm 1.26.11
jruby 9.0.0.0.rc1
java 1.8.0_45
ruby 2.2.1
ubuntu 14.1

Theine config like this
```
base_port: 11000
max_port: 11100
min_free_workers: 2
spawn_parallel: false(true has not working already)
```

I make sure theine_server start and use address 127.0.0.1:11000,but get "Waiting for Theine worker....." after running ``` time theine runner "puts Rails.env" ```

**Comment by ooeyuna** [comment]
i try to change the method ``` connect_worker ``` in ``` lib/client.rb ``` , use ``` @config.base_port+1 ```, connect to the first port, it's working. i guess there is something wrong with drb?

**Comment by ooeyuna** [comment]
i forgot to use screen....

**Comment by scepticulous** [comment]
@ooeyuna how and why are you using screen in this case?
