### ISSUE TITLE
Run RSpec through Theine seems to use the development database

### ISSUE THREAD

**Issue by thedelchop** [mrbrdo/theine#7]
Hi, 

I've been using Theine with great success to launch my server and my console, however, it seems that when I attempt to run RSpec using Theine, it doesn't correctly set the Rails environment to 'test', so I end up using the wrong database.  

Is there a configuration option I'm missing or something I should be doing to get the behavior I'm looking for?

**Comment by adamgotterer** [comment]
I'm having this same problem using Sequel. Any thoughts?

**Comment by mrbrdo** [comment]
Are you using sequel-rails or just sequel?

**Comment by adamgotterer** [comment]
I'm using sequel-rails

On Sat, Jan 17, 2015 at 12:28 PM, Jan Berdajs <notifications@github.com>
wrote:

> Are you using sequel-rails or just sequel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrbrdo/theine/issues/7#issuecomment-70375427>.
>



-- 
Adam Gotterer
516-650-6331
agotterer@gmail.com

**Comment by mrbrdo** [comment]
Try this branch https://github.com/mrbrdo/theine/tree/sequel
e.g. `gem 'theine', github: 'mrbrdo/theine', branch: 'sequel'`

**Comment by mrbrdo** [comment]
@adamgotterer so did you try it?

**Comment by mrbrdo** [comment]
@adamgotterer could you let me know, please?
